WebShop/WebShop/Controllers/CartController.cs
namespace WebShop.App.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;
    using WebShop.Services.Models.BookShop;
    using Services.ServiceControllers;
    using WebShop.Core.Models.Identity;

    [AutoValidateAntiforgeryToken]
    public class CartController : BaseController
    {
        private readonly BookShopService _service;
        private readonly CartService _cartService;
        private readonly UserHelper<ApplicationUser, Guid> _userHelper;

        public CartController(BookShopService service, CartService cartService, UserHelper<ApplicationUser, Guid> userHelper)
        {
            _service = service;
            _cartService = cartService;
            _userHelper = userHelper;
        }

        [HttpPost]
        public IActionResult Remove(int id, string returnUrl)
        {
            var cart = GetCart();

            if (cart.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (cart.ContainsKey(id))
            {
                cart.Remove(id);
            }

            HttpContext.Session.SetString("Cart", JsonConvert.SerializeObject(cart));
            returnUrl = returnUrl.Replace("amp;", "");
            return Redirect(returnUrl);
        }

        [HttpGet]
        public async Task<IActionResult> Add(int id, int quantity, string returnRoute)
        {
            var cart = GetCart();

            if (quantity <= 0)
            {
                quantity = 1;
            }

            if (!await _service.AnyBook(id))
            {
                return RedirectToAction("Index", "Error", 404);
            }

            if (cart.ContainsKey(id))
            {
                cart[id] += quantity;
            }
            else
            {
                cart.Add(id, quantity);
            }

            if (cart.Count == 1)
            {
                TempData["UnfoldCart"] = true;
            }


            HttpContext.Session.SetString("Cart", JsonConvert.SerializeObject(cart));

            return RedirectToAction("Details", "Home", new { ItemId = id, ReturnRoute = returnRoute });
        }

        public IActionResult Clear()
        {
            ClearCart();

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Checkout()
        {
            var cart = GetCart();
            var model = new Cart();
            model.Items = await _cartService.GetShopItems(cart);
            model.TotalPrice = model.Items.Sum(i => i.TotalPrice);

            if (model.Items.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Order()
        {
            var order = new OrderModel()
            {
                TotalPrice = await _cartService.GetTotalPrice(GetCart())
            };
            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> Order(OrderModel model)
        {
            var isValid = ModelState.IsValid;
            var userId = await _userHelper.GetUserId(User);

            if (isValid)
            {
                try
                {

                    var cart = GetCart();

                    if (cart.Count == 0)
                    {
                        ModelState.AddModelError("All", "Invalid cart data!");
                        isValid = false;
                    }
                    else
                    {
                        await _cartService.AddNewOrder(cart, model, userId);
                    }
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("All", e.Message);
                    isValid = false;
                }

            }

            if (!isValid)
            {
                model.TotalPrice = await _cartService.GetTotalPrice(GetCart());
                return View(model);
            }

            ClearCart();
            var invoice = await _cartService.GetCurrentInvoice(userId);
            return View(nameof(OrderDetails), invoice);
        }

        [HttpGet]
        public IActionResult OrderDetails(Invoice model)
        {
            return View(model);
        }

        private void ClearCart()
        {
            HttpContext.Session.SetString("Cart", string.Empty);
        }

        private Dictionary<int, int> GetCart()
        {
            var data = HttpContext.Session.GetString("Cart");
            if (string.IsNullOrWhiteSpace(data))
            {
                return new();
            }

            var cart = JsonConvert.DeserializeObject<Dictionary<int, int>>(data);

            if (cart == null)
            {
                return new();
            }

            return cart;
        }
    }
}

WebShop/WebShop/Controllers/MyOrdersController.cs
namespace WebShop.App.Controllers
{
    using System.Globalization;
    using Microsoft.AspNetCore.Mvc;
    using Services.ServiceControllers;
    using WebShop.Services.Models.MyOrders;
    using WebShop.Services.Models.MyOrders.Enumerations;

    [AutoValidateAntiforgeryToken]
    public class MyOrdersController : BaseController
    {
        private readonly MyOrderService _myOrderService;
        public MyOrdersController(MyOrderService myOrderService)
        {
            _myOrderService = myOrderService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string status, string from, string to, string orderClause)
        {
            var orderStatus = status switch
            {
                "Pending" => OrderStatus.Pending,
                "Shipped" => OrderStatus.Shipped,
                "Delivered" => OrderStatus.Delivered,
                _ => OrderStatus.All
            };

            var orderValue = orderClause switch
            {
                "TotalPriceAsc" => OrderClause.TotalPriceAsc,
                "TotalPriceDesc" => OrderClause.TotalPriceDesc,
                "OrderDateAsc" => OrderClause.OrderDateAsc,
                _ => OrderClause.OrderDateDesc
            };

            var isFromDateValid = DateTime.TryParseExact(from, "yyyy-MM-dd", CultureInfo.InvariantCulture,
                DateTimeStyles.None, out var fromDate);

            var isToDateValid = DateTime.TryParseExact(to, "yyyy-MM-dd", CultureInfo.InvariantCulture,
                DateTimeStyles.None, out var toDate);

            DateTime? fromValue = isFromDateValid ? fromDate : null;
            DateTime? toValue = isToDateValid ? toDate : null;

            var model = new MyOrdersPage()
            {
                OrderStatus = orderStatus,
                OrderClause = orderValue,
                From = fromValue,
                To = toValue,
                HasAnyOrders = await _myOrderService.AnyUserOrdersPresent(User),
                Orders = await _myOrderService.GetUserOrders(User, orderStatus, orderValue, fromValue, toValue)
            };
            return View(model);
        }
    }
}

WebShop/WebShop/Views/Cart/Checkout.cshtml
@{
    ViewData["Title"] = "Checkout";
}
@model Cart

<section id="checkout">
    <h2 class="title">Checkout</h2>
    <div class="order-list">
        @await Html.PartialAsync("Components/_CheckoutItemPartial", Model.Items)
    </div>
    <div class="overall-info">
        @{
            var price = $"{Model.TotalPrice:f2}";

            <p>Total: @price$</p>
        }
    </div>
    <div class="action-list">
        <a asp-controller="Home" asp-action="Index" class="generic-action fas fa-home">Home</a>
        <a asp-controller="Cart" asp-action="Clear" class="cancel fas fa-trash">Clear cart</a>
        <a asp-controller="Cart" asp-action="Order" class="confirm fas fa-angle-double-right">Proceed to payment</a>
    </div>
</section>

WebShop/WebShop/Views/Cart/Order.cshtml
@{
    ViewData["Title"] = "Place an order";
}
@model OrderModel;

<section id="order" class="small-window-field">
    <div class="title-holder">
        <h1 class="title">Order placement</h1>
    </div>
    <form asp-controller="Cart" asp-action="Order" method="post" class="form-list">
        @Html.AntiForgeryToken()
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-field">
            <input type="text" asp-for="Country" placeholder="">
            <label asp-for="Country"></label>
            <span asp-validation-for="Country" class="text-danger"></span>
        </div>
        <div class="form-field">
            <input type="text" asp-for="City" placeholder="">
            <label asp-for="City"></label>
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
        <div class="form-field">
            <input type="text" asp-for="Address" placeholder="">
            <label asp-for="Address"></label>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div class="pricing">
            @{
                var price = $"{Model.TotalPrice:f2}";
                <p>Total: @price$</p>
            }
        </div>
        <div class="centered action-list">
            <a asp-controller="Cart" asp-action="Checkout" class="cancel"><i class="fas fa-caret-left"></i> Go Back</a>
            <button type="submit" class="btn-confirm"><i class="fas fa-check"></i> Place Order</button>
        </div>
    </form>
</section>

WebShop/WebShop/Views/Cart/OrderDetails.cshtml
@{
    ViewData["Title"] = "Invoice";
}
@model Invoice;

<section id="order-status" class="small-window-field">
    <h1 class="title">Order Details</h1>
    <div class="info">
        @{
            var totalPrice = $"{Model.TotalPrice:f2}";

            <p title="Customer name"><i class="fas fa-user"></i><span>@Model.CustomerName</span></p>
            <p title="Phone number"><i class="fas fa-phone"></i><span>@Model.PhoneNumber</span></p>
            <p title="Country"><i class="fas fa-globe"></i><span>@Model.Country</span></p>
            <p title="City"><i class="fas fa-city"></i><span>@Model.City</span></p>
            <p title="Address"><i class="fas fa-map-marker-alt"></i><span>@Model.Address</span></p>
            <p title="Total price"><i class="fas fa-money-bill-alt"></i><span>@totalPrice$</span></p>
        }
    </div>
    <div class="status-icon far fa-check-circle">
        <p>Successful</p>
    </div>
    <div class="action-list">
        <a asp-controller="Home" asp-action="Index" class="fas fa-home primary-btn">Home Page</a>
        <a asp-controller="MyOrders" asp-action="Index" class="fas fa-clipboard-list primary-btn">My orders</a>
    </div>
</section>